// <auto-generated />
using System;
using IK.DAL.ContextClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IK.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251124225205_Mg1")]
    partial class Mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IK.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ActivationCode = new Guid("00000000-0000-0000-0000-000000000000"),
                            ConcurrencyStamp = "14d4815b-5db4-43cb-b40a-03600309d17f",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ozan@ik.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OZAN@IK.COM",
                            NormalizedUserName = "OZAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEBagqgoUvgNlUJqXO4PYu7aqRkSJjo1iHEKW2RAeYzIn7jX24sU8QofI+WQX1Ozh8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "096bf938-d7a6-4d67-9f4b-797ace304953",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "ozan"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ActivationCode = new Guid("00000000-0000-0000-0000-000000000000"),
                            ConcurrencyStamp = "ea088c72-3ff5-429e-8bfe-0dd0dd1c3fbf",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet@ik.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMET@IK.COM",
                            NormalizedUserName = "AHMET",
                            PasswordHash = "AQAAAAIAAYagAAAAEO/7MGp5UdQhAA0uICjnHUFwTrbm5IvO5ZAPEiK3pdS+6i2sPR2/YhHul5qYh8Z25g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d27f9a49-1f01-4e49-ac82-c3b0ed9f0d96",
                            Status = 0,
                            TwoFactorEnabled = false,
                            UserName = "ahmet"
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("AppUserProfiles");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul Kadıköy",
                            BranchName = "Merkez Şube",
                            City = "İstanbul",
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4424),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ankara Etimesgut",
                            BranchName = "Ankara Şube",
                            City = "Ankara",
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4439),
                            Status = 1
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.CareerPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlannedPromotionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetPositionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPositionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TargetPositionId");

                    b.ToTable("CareerPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4529),
                            CurrentPositionId = 1,
                            EmployeeId = 1,
                            Notes = "Başarılı performans",
                            PlannedPromotionDate = new DateTime(2026, 5, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4530),
                            Status = 1,
                            TargetPositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4539),
                            CurrentPositionId = 2,
                            EmployeeId = 2,
                            Notes = "Tecrübeyi artıracak",
                            PlannedPromotionDate = new DateTime(2026, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4540),
                            Status = 1,
                            TargetPositionId = 2
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Departmant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Departmants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4620),
                            DepartmantName = "İK",
                            Description = "İnsan Kaynakları",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4622),
                            DepartmantName = "Yazılım",
                            Description = "Yazılım Geliştirme",
                            Status = 1
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TCKN")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul",
                            AppUserId = 1,
                            BirthDate = new DateTime(2002, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 1,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4736),
                            DepartmanId = 1,
                            Email = "ozan@ik.com",
                            FirstName = "Ozan",
                            Gender = 1,
                            JobType = 1,
                            LastName = "Erel",
                            MaritalStatus = 1,
                            PhoneNumber = "05000000001",
                            PositionId = 1,
                            Salary = 10000m,
                            StartDate = new DateTime(2023, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4741),
                            Status = 1,
                            TCKN = "12345678901"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ankara",
                            AppUserId = 2,
                            BirthDate = new DateTime(1992, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BranchId = 2,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4746),
                            DepartmanId = 2,
                            Email = "ahmet@ik.com",
                            FirstName = "Ahmet",
                            Gender = 1,
                            JobType = 1,
                            LastName = "Baykara",
                            MaritalStatus = 2,
                            PhoneNumber = "05000000002",
                            PositionId = 2,
                            Salary = 9000m,
                            StartDate = new DateTime(2024, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4749),
                            Status = 1,
                            TCKN = "12345678902"
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.EmployeeQualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeQualifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Certifications = "İK Sertifikası",
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4676),
                            Education = "Üniversite",
                            EducationLevel = 3,
                            EmployeeId = 1,
                            Experience = "2 yıl",
                            Languages = "İngilizce",
                            Skills = "MS Office",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Certifications = "MCP",
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4679),
                            Education = "Üniversite",
                            EducationLevel = 3,
                            EmployeeId = 2,
                            Experience = "3 yıl",
                            Languages = "İngilizce",
                            Skills = "C#, ASP.NET",
                            Status = 1
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApplicateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<string>("CVFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicantName = "Mehmet Demir",
                            ApplicateDate = new DateTime(2025, 11, 15, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4813),
                            ApplicationStatus = 1,
                            CVFilePath = "CVs/MehmetDemir.pdf",
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4811),
                            Email = "mehmet@example.com",
                            PhoneNumber = "05001112233",
                            PositionId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            ApplicantName = "Ayşe Yılmaz",
                            ApplicateDate = new DateTime(2025, 11, 20, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4820),
                            ApplicationStatus = 2,
                            CVFilePath = "CVs/AyseYilmaz.pdf",
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4818),
                            Email = "ayse@example.com",
                            PhoneNumber = "05004445566",
                            PositionId = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bonuses")
                        .HasColumnType("money");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("money");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payrolls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bonuses = 500m,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4859),
                            Deductions = 500m,
                            EmployeeId = 1,
                            GrossSalary = 10000m,
                            NetSalary = 9000m,
                            Period = "2025-11",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Bonuses = 300m,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4863),
                            Deductions = 400m,
                            EmployeeId = 2,
                            GrossSalary = 9000m,
                            NetSalary = 8200m,
                            Period = "2025-11",
                            Status = 1
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmantId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxSalary")
                        .HasColumnType("money");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("money");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredEducation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmantId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4909),
                            DepartmantId = 1,
                            MaxSalary = 12000m,
                            MinSalary = 8000m,
                            PositionName = "İK Uzmanı",
                            RequiredEducation = "Üniversite",
                            RequiredExperience = "2 yıl",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4913),
                            DepartmantId = 2,
                            MaxSalary = 15000m,
                            MinSalary = 9000m,
                            PositionName = "Yazılım Geliştirici",
                            RequiredEducation = "Üniversite",
                            RequiredExperience = "3 yıl",
                            Status = 1
                        });
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.WorkHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkHours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4948),
                            EmployeeId = 1,
                            EntryTime = new DateTime(2025, 11, 25, 9, 0, 0, 0, DateTimeKind.Local),
                            ExitTime = new DateTime(2025, 11, 25, 18, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalHours = 9m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 25, 1, 52, 5, 296, DateTimeKind.Local).AddTicks(4954),
                            EmployeeId = 2,
                            EntryTime = new DateTime(2025, 11, 25, 9, 0, 0, 0, DateTimeKind.Local),
                            ExitTime = new DateTime(2025, 11, 25, 18, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            TotalHours = 9m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "13c51905-8b69-4a1b-81ec-ff2ffde5b987",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "198abdb6-874e-49b6-a663-fba4bcb61056",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IK.ENTITIES.Models.AppUserProfile", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.AppUser", "AppUsers")
                        .WithOne("AppUserProfile")
                        .HasForeignKey("IK.ENTITIES.Models.AppUserProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.CareerPlan", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Position", "CurrentPosition")
                        .WithMany()
                        .HasForeignKey("CurrentPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.ENTITIES.Models.Employee", "Employee")
                        .WithMany("CareerPlans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.ENTITIES.Models.Position", "TargetPosition")
                        .WithMany()
                        .HasForeignKey("TargetPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentPosition");

                    b.Navigation("Employee");

                    b.Navigation("TargetPosition");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Departmant", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Branch", "Branch")
                        .WithMany("Departmants")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Employee", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.AppUser", "AppUser")
                        .WithOne("Employee")
                        .HasForeignKey("IK.ENTITIES.Models.Employee", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.ENTITIES.Models.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.ENTITIES.Models.Departmant", "Departmant")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IK.ENTITIES.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Branch");

                    b.Navigation("Departmant");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.EmployeeQualification", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Employee", "Employee")
                        .WithOne("EmployeeQualification")
                        .HasForeignKey("IK.ENTITIES.Models.EmployeeQualification", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.JobApplication", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Payroll", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Employee", "Employee")
                        .WithMany("Payrolls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Position", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Departmant", "Departmant")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departmant");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.WorkHour", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.Employee", "Employee")
                        .WithMany("WorkHours")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IK.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("IK.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IK.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("AppUserProfile")
                        .IsRequired();

                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Branch", b =>
                {
                    b.Navigation("Departmants");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Departmant", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Employee", b =>
                {
                    b.Navigation("CareerPlans");

                    b.Navigation("EmployeeQualification")
                        .IsRequired();

                    b.Navigation("Payrolls");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("IK.ENTITIES.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
